server:
  compression:
    enabled: true
    min-response-size: 1KB
  tomcat:
    max-http-form-post-size: 10MB
    
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: when_authorized
  security:
    enabled: false
    
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - buckets
      - filterConfigCache
      - documentAnalysis
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
  mvc:
    throw-exception-if-no-handler-found: true
    
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{requestId}] - %msg%n"
  level:
    root: INFO
    com.flt.fltspring: INFO
    org.springframework.web: INFO
    
# Azure configuration    
azure:
  document-intelligence:
    endpoint: https://flight-log-scan.cognitiveservices.azure.com/

# Application configuration
app:
  admin-emails: will.janis@gmail.com,lancedesi@msn.com
  
# Rate limiting configuration  
bucket4j:
  enabled: true
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  methods:
    - name: default
      cache-name: buckets
      rate-limit:
        cache-key: 1
        bandwidths:
          - capacity: 1
            refill-capacity: 1
            time: 2
            unit: seconds
            initial-capacity: 1
            refill-speed: interval
  filters:
    - id: filter1
      cache-name: buckets
      url: .*
      rate-limits:
        - cache-key: getRemoteAddr()
          post-execute-condition: getStatus() eq 200
          bandwidths:
            - capacity: 10
              refill-capacity: 1
              time: 10
              unit: seconds
              initial-capacity: 5
              refill-speed: interval