name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            flightlogscanner/flightlogscan:latest
            flightlogscanner/flightlogscan:${{ github.sha }}
          platforms: linux/amd64

  deploy:
    needs: build
    runs-on: [self-hosted, hetzner]

    steps:
      - name: Run deploy script
        run: /opt/flightlogscan/bin/deploy.sh ${{ github.sha }}