name: Build and Deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [infra_updated]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            flightlogscanner/flightlogscan:latest
            flightlogscanner/flightlogscan:${{ github.sha }}
          platforms: linux/amd64

  deploy:
    runs-on: [self-hosted, hetzner]
    if: github.event_name == 'push'
    needs: build
    steps:
      - name: Run deploy script
        run: |
          /opt/flightlogscan/bin/deploy.sh ${{ github.sha }}

  deploy_from_infra:
    runs-on: [self-hosted, hetzner]
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: Run deploy script
        run: |
          /opt/flightlogscan/bin/deploy.sh ${{ github.event.client_payload.sha }}